AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public virtual DbSet<Species> Species{ get; set; }
    public DbSet<Breeds> Breeds { get; set; }
    
    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Models/Breeds.cs
namespace AnimalShelter.Models
{
  public class Breeds
  {
    public int BreedsId { get; set; }
    public string AnimalName { get; set; }
    public string Gender {get; set; }
    public string Date {get; set; }

    public int SpeciesId {get; set;}
    public virtual Species Species {get; set;}
  }
}

AnimalShelter/Models/Species.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
  public class Species
    {
        public Species()
        {
            this.Breeds = new HashSet<Breeds>();
        }

        public int SpeciesId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Breeds> Breeds { get; set; }
    }
}

AnimalShelter/Controllers/BreedsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AnimalShelter.Controllers
{
  public class BreedsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public BreedsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Breeds> model = _db.Breeds.Include(breeds => breeds.Species).ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
        Breeds thisBreed = _db.Breeds.FirstOrDefault(breeds => breeds.BreedsId == id);
        return View(thisBreed);
    }

    public ActionResult Create()
    {
        ViewBag.SpeciesId = new SelectList(_db.Species, "SpeciesId", "Name");
        return View();
    }

    [HttpPost]
    public ActionResult Create(Breeds breed)
    {
        _db.Breeds.Add(breed);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

AnimalShelter/Controllers/SpeciesController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Controllers
{
  public class SpeciesController : Controller
  {
    private readonly AnimalShelterContext _db;

    public SpeciesController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Species> model = _db.Species.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Species species)
    {
      _db.Species.Add(species);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Species thisSpecies = _db.Species.FirstOrDefault(species => species.SpeciesId == id);
      return View(thisSpecies);
    }

    // public ActionResult Edit(int id)
    // {
    //   var thisCategory = _db.Species.FirstOrDefault(category => category.CategoryId == id);
    //   return View(thisCategory);
    // }

    // [HttpPost]
    // public ActionResult Edit(Category category)
    // {
    //   _db.Entry(category).State = EntityState.Modified;
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }

    // public ActionResult Delete(int id)
    // {
    //   var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
    //   return View(thisCategory);
    // }

    // [HttpPost, ActionName("Delete")]
    // public ActionResult DeleteConfirmed(int id)
    // {
    //   var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
    //   _db.Categories.Remove(thisCategory);
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }
  }
}

AnimalShelter/Views/Breeds/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Breeds

<h4>Add a new animal</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.AnimalName)
    @Html.TextBoxFor(model => model.AnimalName)
    @Html.LabelFor(model => model.Gender)
    @Html.TextBoxFor(model => model.Gender)
    @Html.LabelFor(model => model.Date)
    @Html.TextBoxFor(model => model.Date)

     @Html.LabelFor(model => model.Species)
    @Html.DropDownList("SpeciesId")

    <input type="submit" value="Add new animal" />
}
<p>@Html.ActionLink("Show all animals", "Index")</p> 

AnimalShelter/Views/Breeds/DeleteAll.cshtml
@{
  Layout = "_Layout";
}

<h1>Your list has been cleared!</h1>
<p><a href="/breeds">Back to list.</a></p>

AnimalShelter/Views/Breeds/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Breeds

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.AnimalName): @Html.DisplayFor(model => model.AnimalName)<h3>
<h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)<h3>
<h3>@Html.DisplayNameFor(model => model.Date): @Html.DisplayFor(model => model.Date)<h3>
<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Breeds/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Breeds>;

<h1>Animal Breeds</h1>

<ul>
  @foreach(Breeds breed in Model)
  {
      <li>@Html.ActionLink($"{breed.AnimalName}", "Details", new { id = breed.SpeciesId })| @breed.Species.Name</li>
  }
</ul>

<p>@Html.ActionLink("Add new animal breed", "Create")</p>

AnimalShelter/Views/Breeds/New.cshtml
@{
  Layout = "_Layout";
}

<h1>Add a new animal breed to @Model.Name</h1>

<form action="/species/@Model.Id/breeds" method="post">
  <input id="speciesId" name="speciesId" type="hidden" value="@Model.Id">
  <label for="breedName">type name</label>
  <input id="breedName" name="breedName" type="text">
  <button type='submit'>Add type</button>
</form>

AnimalShelter/Views/Breeds/Show.cshtml
@{
  Layout = "_Layout";
}

<h1>Animal Shelter Type Details: </h1>

<h2>@Model["breeds"].AnimalName/h2>
<h3>Species: @Model["species"].Name</h3>

<a href='/species/@Model["species"].Id/breed/new'>Add another animal type.</a>
<a href='/species'>View all species</a>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Animal Shelter!</h1>
<p>@Html.ActionLink("See all species", "Index", "Species")

</p> 
<p>@Html.ActionLink("See all animal breeds", "Index", "Breeds")

</p>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

AnimalShelter/Views/Species/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Species

<h4>Add a new species</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add new species" />
}
<p>@Html.ActionLink("Show all species", "Index")</p>

AnimalShelter/Views/Species/Details.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;
@model AnimalShelter.Models.Species;

<h2>Species Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<ul>
@if (@Model.Breeds.Count == 0)
{
  <p>no breeds found</p>
}

@foreach (Breeds breed in @Model.Breeds)
{
  <li>Description: @breed.AnimalName</li>
}
</ul>

<p>@Html.ActionLink("Back to Species", "Index")</p>
<p>@Html.ActionLink("Edit Species", "Edit", new { id = Model.SpeciesId })</p>
<p>@Html.ActionLink("Delete Species", "Delete", new { id = Model.SpeciesId })</p>

AnimalShelter/Views/Species/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Species>;

<h1>Species</h1>

@if (@Model.Count == 0)
{
  <h3>No animals have been added yet!</h3>
} 

@foreach (Species animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.SpeciesId })</li>
}

<p>@Html.ActionLink("Add new animal", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>